name: 'Run Quality Checks'
description: 'Runs linting and type checking'

runs:
  using: 'composite'
  steps:
    - name: Lint
      shell: bash
      run: npm run lint
    
    - name: Typecheck
      shell: bash
      run: npm run typecheck
    
    - name: Check import boundaries
      shell: bash
      run: npm run lint:import-boundaries
